// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llisxehwxhrqdqxhwbbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsaXN4ZWh3eGhycWRxeGh3YmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDE5NDEsImV4cCI6MjA3MDMxNzk0MX0.AomZPY39LhVcqXMWXwEOxZlj2lXJyUTqJO73FcYYdZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});